apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: jenkins-rs
spec: 
  minReadySeconds: 5
  replicas: 5
  selector: 
    matchLabels:
      apps: jenkins
    template: 
      metadata:
        name: jenkins
        labels: 
          apps: jenkins
      spec:
        containers:
          - name: jenkins
            image: jenkins/jenkins:lts-jdk11
            ports:
              - containerPort: 8080
          - name: alpine
            image: alpine:3
            args:
              - sleep
              - 1d
