---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec: 
  minReadySeconds: 2
  replicas: 4
  selector:
    matchLabels: 
      apps: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        apps: nginx
    spec: 
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
            
