---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec: 
  minReadySeconds: 2
  replicas: 4
  template:
    metadata:
      name: nginx-pod
    spec: 
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
            
