---
apiVersion: v1
kind: Pod
metadata: 
  name: exmpl-3
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        containerPort: 80
    - name: alpine1
      image: alpine
      args:
        - sleep
        - 1d
    - name: alpine3
      image: alpine
      args:
        - sleep
        - 10s
        