---
apiVersion: v1
kind: pod
metadata: 
  name: restartsnever
spec:
  restartPolicy: Never
  containers:
    - name: alpine
      image: alpine
      args:
        - sleep
          3s
          
      