apiVersion: batch/v1
kind: CronJob
metadata:
  name: livedata
spec: 
  schedule: '* * * * *'
  jobTemplate: 
    metadata: 
      name: livedata
    spec:
      template:
        metadata:
          name: livedata
        spec:
          restartPolicy: Never
          containers:
            - name: alpine1
              image: alpine
              command:
                - sleep
                - 3s