---
apiVersion: batch
kind: Job
metadata: 
  name: myjob
spec: 
  template:
    metadata:
      name: myjobpod
  spec:
    containers:
      - image: alpine
        command:
          - sllep
          - 10s

