---
apiVersion: batch
kind: Job
metadata: 
  name: hellojob
spec: 
  template:
    metadata:
      name: jobpod
  spec:
    containers:
      - image: alpine
        command:
          - sllep
          - 10s

