---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: Periodicjob
spec:
  schedule: '* * * * *' 
  jobTemplate: 
    metadata:
      name: getlivedata
    spec:
      template:
        metadata:
          name: livedatapod
        spec:
          containers:
            - name: alpine
              image: alpine
              command:
                - sleep
                - 2s

      
    