---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: Periodicjob
spec:
  schedule: '* * * * *' 
  jobTemplate: 
    metadata:
      name: nowdata
    spec:
      backoffLimit: 2
      template:
        metadata:
          name: livedata
        spec:
          restartPolicy: OnFailure
          containers:
            - name: alpine
              image: alpine
              command:
                - sleep
                - 2s

      
    