---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: periodicjob
spec:
  schedule: '* * * * *' 
  jobTemplate: 
    metadata:
      name: getlivedata
    spec:
      template:
        metadata:
          name: livedata
        spec:
          restartPolicy: Never
          containers:
            - name: alpine1
              image: alpine
              command:
                - sleep
                - 3s
      
    